spring:
  application:
    name: SpringAI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.5-flash
      embedding:
        options:
          model: gemini-embedding-001
          dimensions: 1536
    vectorstore:
      qdrant:
        host: 127.0.0.1       # Qdrant 服务地址
        port: 6334             # gRPC 端口，默认 6334
        api-key: ""
        collection-name: spring001  # 创建的 collection 名称
        use-tls: false         # 本地不需要 TLS
        initialize-schema: false  # 已经手动创建过 schema，这里设为 false
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    mcp:
      client:
        request-timeout: 20s
        stdio:
          servers-configuration: classpath:/mcp/mcp-servers-config.json


  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/itheima?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyIntlisBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 123456


  http:
    codecs:
      max-in-memory-size: 20MB

  servlet:
   multipart:
    max-file-size: 30MB        # 单个文件上限
    max-request-size: 100MB     # 整个请求上限（所有文件+表单）

logging:
  level:
    org.springframework.ai: debug
    com.example.springai: debug